---
- name: Create Nginx web server
  hosts: devkube
  tasks:
  - name: Update APT Package 
    ansible.builtin.apt:
      update_cache: true
  - name: Install nginx Package
    ansible.builtin.apt:
      name: nginx
      state: latest
  - name: Start nginx server
    ansible.builtin.service:
      name: nginx
      state: started
